### ISSUE TITLE
Change alert message when importing tasks

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#209]
It doesn't make sense to use the default delete alert

**Comment by angrykoala** [comment]
![screenshot from 2017-10-22 15-29-22](https://user-images.githubusercontent.com/5960567/31862430-cd3acf40-b73d-11e7-8263-ed5784d4595d.png)
_Current modal_

Them essage should read something like: "Importing tasks will remove all your tasks, are you sure you want to continue?" or something like that

**Comment by jhdoak** [comment]
I'd like to take a look and give this a shot.

**Comment by jhdoak** [comment]
@angrykoala I want to make sure tests are still passing after the fix an PR. Having issues running the tests in both master and dev branches. Is this something you're seeing, or unique to me?

```
No coverage information was collected, exit without writing coverage information
/Users/justin/Documents/development/angrykoala/gaucho/node_modules/just-extend/index.js:40
      throw new Error('expected object, got ' + arg);
      ^

Error: expected object, got function FakeXMLHttpRequest(config) {
    EventTargetHandler.call(this);
    this.readyState = FakeXMLHttpRequest.UNSENT;
    this.requestHeaders = {};
    this.requestBody = null;
    this.status = 0;
    this.statusText = "";
    this.upload = new EventTargetHandler();
    this.responseType = "";
    this.response = "";
    this.logError = configureLogError(config);

    if (sinonXhr.supportsTimeout) {
        this.timeout = 0;
    }

    if (sinonXhr.supportsCORS) {
        this.withCredentials = false;
    }

    if (typeof FakeXMLHttpRequest.onCreate === "function") {
        FakeXMLHttpRequest.onCreate(this);
    }
}
    at extend (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/just-extend/index.js:40:13)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/nise/lib/fake-xhr/index.js:651:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/nise/lib/fake-server/index.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/nise/lib/index.js:4:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/sinon/lib/sinon/sandbox.js:8:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/sinon/lib/sinon.js:11:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/test/suite.test.js:4:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at runFn (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/async/lib/async.js:52:16
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/async/lib/async.js:361:13
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/async/lib/async.js:52:16
    at done (/Users/justin/Documents/development/angrykoala/gaucho/node_modules/async/lib/async.js:246:17)
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/async/lib/async.js:44:16
    at /Users/justin/Documents/development/angrykoala/gaucho/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1754:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jhdoak** [comment]
I'm also wondering about the buttons. Given an alert like "Importing tasks will remove all your tasks, are you sure you want to continue?", does having buttons that say "Yes, delete it!" and "No, keep it" make sense?

Assuming we want different button text based on each alert, would it be best to pass button text as arguments to the constructor of DeleteConfirmationAlert and set the text that way, or create a different Alert class with different hard-coded button text?

**Comment by angrykoala** [comment]
Ok, the first error you are seeing is the first time I saw. Please try to execute the tests with a fresh clone to check if it is caused by your changes or by a broken dependency.

About the buttons, if you check the DeleteConfirmationAlert class, it accepts an "options" argument, so you could easily change the texts by passing those options:
`new DeleteConfirmationAlert(myText, { confirmButtonText: "mytext", cancelButtonText:"myotherText"});`

Feel free to modify the classes in AppAlert with improvements or subclasses, but avoid changing the interface to DeleteConfirmationAlert, as it is made with those default texts to avoid repeating code

**Comment by jhdoak** [comment]
@angrykoala - I just made an edit to my first comment. It looks like the broken tests are related to a recent release of just-extend, which is a dependency of sinon. I'll see if I can roll back to an older version of sinon in order to get the tests running.

Thanks for helping point me in the right direction.

**Comment by angrykoala** [comment]
remove the node_modules folder, put the exact version of sinon in the package.json (remove the ^) and execute npm install again. I'll check about broken dependencies later. Thanks for noticing

**Comment by jhdoak** [comment]
I tried to install sinon locked to 4.0.0, but just-extend is a dependency of a dependency of sinon, so I couldn't control the version that deeply.

For now, the best I could do was run an npm install, remove just-extend from node_modules, and then explicitly install just-extend version 1.1.22.

```
npm install && rm -rf node_modules/just-extend/ && npm install just-extend@1.1.22
```

**Comment by jhdoak** [comment]
I've come across some other questions/potential changes.

- On clicking "Clear Tasks", change buttons to be "Yes, delete **them**!" and "No, keep **them**"
- Pressing "Clear Tasks" redirects to the tasks page behind the alert, but clicking "Import Tasks" and selecting a tasks.json stays on the configuration page behind the alert. Is this differing functionality intentional?

I could pretty easily change the buttons as a part of the fix for this issue, if that's appropriate. The other point might require its own issue, if there is a desired change.

**Comment by angrykoala** [comment]
1. I like the idea of changing those texts.
2. No, it is not intentional, and it is a known issue, I forgot to create an issue for that. Thanks for spotting it
